name: GitHub Actions Demo - If condition
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - if: true
        name: If conditiion True
        run: |
          echo "The condition met Step 1"
          echo "The condition met Step 2"
          
      - run: echo "Out of if"
        
      
